### ISSUE TITLE
grub menu in boxes waits for ~15 seconds

### ISSUE THREAD

**Issue by sax** [vagrant-smartos/vagrant-smartos-packager#6]
If we could find some way of skipping option prompts in the boot loader, we'd save a significant amount of time waiting when boxes boot.

**Comment by tylerflint** [comment]
That can be done when creating the image. I suppose I could take this, it’s a pretty simple change.

**Comment by sax** [comment]
That would be awesome. It would probably take me a lot longer to figure this out.

I can roll out new boxes to vagrantcloud if you make any changes to the creation scripts.

**Comment by tylerflint** [comment]
Sorry for the delay on this. I just pushed a commit that adds a script to drop the grub delay to 0 seconds. It's in the bin directory.

**Comment by sax** [comment]
Awesome! Thank you so much for this. I want to roll out some new boxes in the next few weeks with the latest images, so this will be extremely helpful.
